### ISSUE TITLE
Notepad3DS crashes when more than one screen of text is written

### ISSUE THREAD

**Issue by SSQ123** [RMcTn/Notepad3DS#3]
On Luma3DS notepad3ds crashes with Data Abort error on ARM9 CPU when more than one screen of text is written. Don't have the dump so can't post it but gonna get the dump from NAND.

**Comment by MaeveMcT** [comment]
Hey, thanks for trying the program out! Could you give an example of some text that causes the crash? I've tried filling up the screen with text but I'm not getting any faulty behaviour.

**Comment by SSQ123** [comment]
I've tried to write a fanfiction but it crashes before I can go  below the bottom of the screen. Maybe it was an older version?

**Comment by MaeveMcT** [comment]
Could you tell me what version you were using? It should say something like
Notepad3DS version: x.x
On the bottom screen when the program is running.

**Comment by SSQ123** [comment]
I downloaded the newest version and it still crashes but here's the dump:
[notepad.zip](https://github.com/RMcTn/Notepad3DS/files/1522283/notepad.zip)

**Comment by MaeveMcT** [comment]
I managed to recreate it. I'll look into this more

**Comment by SSQ123** [comment]
Thanks.

**Comment by SSQ123** [comment]
Fixed yet?

**Comment by MaeveMcT** [comment]
@SSQ123 Should now be fixed and available in the new release (1.1.2). Thanks for pointing this out!

**Comment by SSQ123** [comment]
Welcome love helping software development.
